#!/usr/bin/env node
// CHANGELOG.md is the single source for "what's new". This turns it into the two things that
// actually get read: the GitHub release body, and a page on myjobseeker.ai.
//
//   node scripts/release-notes.mjs --version v0.4.0            print that release's notes
//   node scripts/release-notes.mjs --latest                    print the newest release's notes
//   node scripts/release-notes.mjs --html <site-dir>           write <site-dir>/whats-new.html
//
// Why generated rather than written twice: a release is the moment you are least inclined to
// carefully re-word the same list in a second place, so the second place is where the drift starts.
// Dependency-free, like everything else here.

import { promises as fs } from "fs";
import path from "path";
import { fileURLToPath } from "url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

// A release is "## v<x> — <date>" followed by bullets, up to the next "## ".
function parse(md) {
  const out = [];
  const re = /^##\s+(v[\d.]+)\s+—\s+(.+)$/gm;
  let m;
  while ((m = re.exec(md))) {
    const start = m.index + m[0].length;
    const next = md.indexOf("\n## ", start);
    out.push({
      version: m[1],
      date: m[2].trim(),
      body: md.slice(start, next === -1 ? undefined : next).trim(),
    });
  }
  return out;
}

// Markdown bullets -> HTML. Only the three things this file is allowed to contain: **bold**,
// `code`, and links. Anything richer belongs in the commit message, not in a user-facing list.
const esc = (s) => s.replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c]);
const inline = (s) =>
  esc(s)
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/`(.+?)`/g, "<code>$1</code>")
    .replace(/\[(.+?)\]\((.+?)\)/g, '<a href="$2">$1</a>');

function bullets(body) {
  const items = [];
  for (const raw of body.split("\n")) {
    const line = raw.trim();
    if (line.startsWith("- ")) items.push(line.slice(2));
    else if (items.length && line) items[items.length - 1] += " " + line; // wrapped continuation
  }
  return items;
}

async function main() {
  const args = process.argv.slice(2);
  const md = await fs.readFile(path.join(ROOT, "CHANGELOG.md"), "utf8");
  const releases = parse(md);
  if (!releases.length) {
    console.error("release-notes: no '## vX.Y.Z — date' sections found in CHANGELOG.md");
    process.exit(1);
  }

  const htmlIdx = args.indexOf("--html");
  if (htmlIdx !== -1) {
    const dest = args[htmlIdx + 1];
    if (!dest) {
      console.error("release-notes: --html needs the site directory");
      process.exit(64);
    }
    // Rendered against the site's own stylesheet and nav, so it is a page of the site rather than a
    // dump of a text file inside one.
    const page = `<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>What's new — JobSeeker</title>
<meta name="description" content="Every JobSeeker release, in plain language.">
<link rel="icon" href="img/mark.png">
<meta property="og:type" content="website">
<meta property="og:url" content="https://myjobseeker.ai/whats-new.html">
<meta property="og:title" content="What's new — JobSeeker">
<meta property="og:description" content="Every JobSeeker release, in plain language.">
<meta property="og:image" content="https://myjobseeker.ai/img/og.png">
<meta name="twitter:card" content="summary_large_image">
<link rel="stylesheet" href="style.css">
<script>document.documentElement.className+=" js-reveal"</script>
</head><body>
<!-- Generated by scripts/release-notes.mjs in the jobseeker repo, from CHANGELOG.md.
     Do not edit here: the next release regenerates it and your edit is gone. -->
<header class="nav">
  <a class="wordmark" href="index.html"><img src="img/mark-ink.png" alt=""><span>JOBSEEKER</span></a>
  <nav>
    <a href="how-it-works.html">How it works</a>
    <a href="privacy.html">Privacy</a>
    <a href="install.html">Install</a>
    <a class="on" href="whats-new.html">What's new</a>
    <a href="https://github.com/cventour/jobseeker">GitHub</a>
    <a class="navbtn" href="https://github.com/cventour/jobseeker/releases/latest">Download Latest Release</a>
  </nav>
</header>
<main>
  <section class="hero">
    <p class="eyebrow">What's new</p>
    <h1>Every release,<br><mark>in plain language.</mark></h1>
    <p class="lede">What changed and whether it matters to you. No release notes written for
      developers.</p>
  </section>
  <section class="rels">
${releases
  .map(
    (r, i) => `    <details class="rel"${i === 0 ? " open" : ""}>
      <summary>
        <span class="rel-v">${esc(r.version)}</span>
        <span class="rel-d">${esc(r.date)}</span>
        ${i === 0 ? '<span class="rel-tag">latest</span>' : ""}
      </summary>
      <ul class="problems">
${bullets(r.body).map((b) => `        <li>${inline(b)}</li>`).join("\n")}
      </ul>
    </details>`
  )
  .join("\n")}
  </section>
  <section>
    <p class="sub">Older versions and the full technical history are on
      <a href="https://github.com/cventour/jobseeker/releases">GitHub</a>.</p>
  </section>
</main>
<footer class="foot">
  <p>JobSeeker runs on your own Mac. <a href="privacy.html">Privacy</a> ·
    <a href="https://github.com/cventour/jobseeker">Source</a></p>
</footer>
<script src="reveal.js"></script>
</body></html>
`;
    await fs.writeFile(path.join(dest, "whats-new.html"), page);
    console.log(`wrote ${path.join(dest, "whats-new.html")} — ${releases.length} release(s)`);
    return;
  }

  const vIdx = args.indexOf("--version");
  const want = vIdx !== -1 ? args[vIdx + 1] : null;
  const r = want ? releases.find((x) => x.version === want) : releases[0];
  if (!r) {
    console.error(`release-notes: ${want} is not in CHANGELOG.md`);
    process.exit(1);
  }
  // Exactly what goes in the GitHub release body.
  process.stdout.write(`${r.body}\n\n---\n\nInstall or upgrade: download below, unzip, double-click **JobSeeker Setup.command**. First time, right-click it and choose Open — macOS asks that of anything not signed by a registered developer. Your existing data and settings are untouched.\n`);
}

main().catch((e) => {
  console.error("release-notes: " + (e?.message || e));
  process.exit(1);
});
